export const addtodo = [
  {
    isSelected: true,
    heading: "Review Journey Builder Ui",
    cont: "Review Journey builder ui with Deeksha,give her feedbacks ",
    span: "Read More",
    color: "#0f0",
    comcolor: "grey",
    date: "Today at 4.40 pm",
    compl: "Task finished on 18July",
  },
  {
    isSelected: true,
    heading: "Review Journey1",
    cont: "Review Journey  ",
    span: "Read More",
    color: "#ff0",
    comcolor: "grey",
    date: "Today at 4.40 pm",
    compl: "Task finished on 15July",
  },
  {
    isSelected: true,
    heading: "Review Journey2",
    cont: "Review Journey  ",
    span: "Read More",
    color: "#f00",
    comcolor: "grey",
    date: "Today at 4.40 pm",
    compl: "Task finished on 19July",
  },
  {
    isSelected: false,
    heading: "Review Journey3",
    cont: "Review Journey  ",
    span: "Read More",
    color: "#f00",
    comcolor: "grey",
    date: "Today at 4.40 pm",
    compl: "Task finished on 17July",
  },
];
